# Generated by Django 6.0.4 on 2026-07-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_otp_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
