# Generated by Django 6.0.4 on 2026-05-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_membership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
