# Generated by Django 6.0.4 on 2026-05-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='contribution_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], max_length=50, null=True),
        ),
    ]
