# Generated by Django 6.0.4 on 2026-05-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_group_contribution_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='total_rounds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
