# Generated by Django 6.0.4 on 2026-07-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_group_duration_group_end_date_group_total_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
