# Generated by manually for DemoProfile model

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_slug', models.CharField(blank=True, max_length=50)),
                ('trust_score', models.PositiveIntegerField(default=0)),
                ('payout_position', models.PositiveIntegerField(default=0)),
                ('is_current_winner', models.BooleanField(default=False)),
                ('monnify_account_number', models.CharField(blank=True, max_length=20)),
                ('monnify_bank_name', models.CharField(blank=True, max_length=100)),
                ('monnify_account_name', models.CharField(blank=True, max_length=200)),
                ('offline_payin_code', models.CharField(blank=True, max_length=50)),
                ('days_overdue', models.PositiveIntegerField(default=0)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('bvn_match', models.CharField(blank=True, max_length=20)),
                ('is_demo_user', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_profile', to='authentication.customuser')),
            ],
            options={
                'db_table': 'demo_demoprofile',
            },
        ),
    ]
