# Generated by Django 6.0.4 on 2026-07-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='demoprofile',
            table=None,
        ),
    ]
